#######################################################################
# This file contains the services requried in the install and run step
#######################################################################
version: "2.3"
services:
    opsi:
        image: opsi-server
        container_name: opsi-server
        hostname: opsi
        volumes:
            - /srv/config/opsi/var/lib/opsi:/var/lib/opsi
            - /srv/config/opsi/etc/opsi/:/etc/opsi
            - /srv/config/opsi/tftpboot:/tftpboot
            - /srv/config/opsi/var/log/opsi:/var/log/opsi
            - /srv/config/opsi/etc/samba:/etc/samba
        environment:
            - EXTERNAL_IP=10.254.6.1
            - DOMAIN=magis.school
            - OPSI_USER=opsi-user
            - OPSI_PASSWORD=Test123
        ports:
            - "4447:4447"
            - "445:445"
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/udp"
            - "69:69/udp"
        entrypoint: /opt/run.sh
